In [7]:
from ucimlrepo import fetch_ucirepo 
from sklearn import model_selection

## Isolet

In [4]:
# fetch dataset 
isolet = fetch_ucirepo(id=54) 
  
# data (as pandas dataframes) 
X = isolet.data.features 
y = isolet.data.targets 
  
# metadata 
print(isolet.metadata) 
  
# variable information 
print(isolet.variables) 

{'uci_id': 54, 'name': 'ISOLET', 'repository_url': 'https://archive.ics.uci.edu/dataset/54/isolet', 'data_url': 'https://archive.ics.uci.edu/static/public/54/data.csv', 'abstract': ' Goal: Predict which letter-name was spoken--a simple classification task.', 'area': 'Computer Science', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 7797, 'num_features': 617, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1991, 'last_updated': 'Fri Feb 16 2024', 'dataset_doi': '10.24432/C51G69', 'creators': ['Ron Cole', 'Mark Fanty'], 'intro_paper': {'title': 'Spoken letter recognition', 'authors': 'Fanty, M., Cole, R.', 'published_in': 'Advances in Neural Information Processing Systems 3', 'year': 1991, 'url': None, 'doi': None}, 'additional_info': {'summary': 'This data set was generated as follows. 150 subjects spoke the name of each le

In [8]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.33, random_state=42)

# print(X_train.to_numpy())

[[-0.4232 -0.0238  0.0716 ... -0.4286 -0.6398 -0.8012]
 [-0.5044 -0.1224 -0.0418 ... -0.0666 -0.2    -0.4858]
 [-0.488   0.1654  0.3468 ...  0.0096  0.1428 -0.0476]
 [-0.575  -0.125   0.1    ...  0.7172  0.602   0.5078]
 [-0.3994  0.2064  0.5442 ... -0.1112 -0.2    -0.7778]]


## Communities and Crime

In [9]:
# fetch dataset 
communities_and_crime = fetch_ucirepo(id=183) 
  
# data (as pandas dataframes) 
X = communities_and_crime.data.features 
y = communities_and_crime.data.targets 